version: '3'

services:
  pwn-all:
    build: ./pwn_all
    image: ripples/ctf-pwn-all
    volumes:
      - ./scripts:/var/pwn

  receive-flag:
    build: ./receive_flag
    image: ripples/ctf-receive-flag
    volumes:
      - ./scripts:/var/pwn
    ports:
      - "8888:8888"
